config/routes.rb
Rails.application.routes.draw do
  # following are the route for system function in system controllersd
  root 'system#index'
  post "/system/login", to: "system#login"
  get "/system/login", to: "system#index"
  get "/system/logout", to: "system#logout"

  # following are the route for students in students controller
  get "/system/students", to: "students#dashboard"
  get "/system/students/request_advice", to: "students#advice"
  get "/system/students/request_advice/new_student", to: "students#new_student"
  get "/system/students/request_advice/continue_student", to: "students#continue_student"
  post "/system/students/request_advice/form_submit", to: "students#form_submit"
  post "/system/students/request_advice/result", to: "students#result"
  get "/system/students/request_advice/result", to: "students#history"
  get "/system/students/advice_history", to: "students#history"
  get "/system/students/help", to: "students#help"
  post "/system/students/show", to: "students#show"
  get "/system/students/show", to: "students#show"
  post "/system/students/edit", to: "students#edit"
  get "/system/students/edit", to: "students#edit"
  patch "/system/students/update", to: "students#update"
  put "/system/students/update", to: "students#update"
  patch "/system/students", to: "students#dashboard"
  get "/system/students/enrolments", to: "students#enrolments"

  # following are the route for staffs in staffs controller
  get "/system/staffs", to: "staffs#dashboard"
  get "/system/staffs/current_appointment", to: "staffs#appointment"
  get "/system/staffs/advice_history", to: "staffs#history"
  post "/system/staffs/show_advice", to: "staffs#show"
  get "/system/staffs/show_advice", to: "staffs#show"
  get "/system/staffs/help", to: "staffs#help"
end

app/models/student.rb
class Student < ApplicationRecord
  has_secure_password

  def self.get_name(s_id)
    name = Student.where(account: s_id).pluck(:name).first
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :user_identify
  # account: a1713245 password: secret

  def dashboard
    # student profile
  end

  def enrolments
    @enrolments=Enrolment.where(student_ID: current_user.account)
    @courses=Course.all
  end

  def advice
    # divert into different form
  end

  def new_student
    # form fo new student
  end

  def continue_student
    # form fo continue student
  end

  def form_submit
    if params.has_key?(:new_or_continue)
      if params[:new_or_continue] == "No"
        redirect_to '/system/students/request_advice/continue_student'
        return
      elsif params[:new_or_continue] == "Yes"
        redirect_to '/system/students/request_advice/new_student'
        return
      end
    end
  end

  def history
    # view at moment, wait for model
    @user = current_user.account
    @advices = CourseAdvice.where(student_ID: @user)
  end

  def help
    # just for help
  end

  def show
    # for showing detail of each advice
    @id = params[:advice_id] || session[:id]
    @advices = CourseAdvice.where(advice_ID: @id)

    @advices.each do |advice|
      if advice.student_ID != current_user.account
        redirect_to "/system/students/advice_history", :alert => "You have no permission to view this resource"
      end
    end

    if params[:advice_id]
      session[:id] = params[:advice_id]
    end

    @advices.each do |advice|
      @a_ID = advice.advice_ID
      @date = advice.date
      @note = advice.note

      @s_ID = advice.student_ID

      @year = advice.degree_year
      @teaching_period = advice.teaching_period

      raw_course_IDs = advice.course_ID
      @course_IDs = YAML.load(raw_course_IDs.delete': ')
    end

    @selected_core_courses = Program.list_program_courses("core", @course_IDs, false, year: @year,teaching_period: @teaching_period)
    @selected_electives = Program.list_program_courses("elective", @course_IDs, false, year: @year,teaching_period: @teaching_period)

  end

  def edit
    @student = current_user.account
    respond_to do |format|
      format.html {render :edit, locals: { student: @student} }
    end
  end

  def update
    student = current_user
    @student = current_user.account
    respond_to do |format|
      format.html do
        if student.update(params.require(@student).permit(:expected_completion))
          flash[:success] = 'Expected completion updated successfully'
          redirect_to system_students_path
        else
          flash.now[:error] = "Error updating expected completion"
          render :edit, locals: { student: student}
        end
      end
    end
  end

  def result

    @selected_core_courses = []
    @selected_electives = []

    if params.has_key?(:year) && params.has_key?(:teaching_period)

      @selected_core_courses = Program.list_program_courses( "core",plan: current_user.plan,year: params[:year],teaching_period: params[:teaching_period])
      @selected_electives = Program.list_program_courses( "elective",plan: current_user.plan,year: params[:year],teaching_period: params[:teaching_period])

      @selected_courses = @selected_core_courses + @selected_electives

      CourseAdvice.save_advice_details(current_user.account, @selected_courses, params[:year], params[:teaching_period])

    end

  end

  private
    def user_identify
      if current_user.is_a?(Student)
        # it's an instance of student
      else
        redirect_to root_url, :alert => "You must login as student to view this resource"
      end
    end
  end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/advice.html.erb
<%= semantic_flash %>

<div class="six ui buttons">
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Dashboard
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/enrolments' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Enrolments
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>
  <button class="ui animated blue disabled button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/request_advice' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Request Advice
      </div>
      <div class="hidden content">
        <i class="users icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/advice_history' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Advice History
      </div>
      <div class="hidden content">
        <i class="clipboard list icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui vertical animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/help' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Help
      </div>
      <div class="hidden content">
        <i class="question circle icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated fade red button" tabindex="0" style="padding: 0">
    <%= link_to '/system/logout' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Logout
      </div>
      <div class="hidden content">
        <i class="sign-out icon"></i>
      </div>
    <% end %>
  </button>

</div>
<br/><br/><br/>

<div style="background-color: #DCE9F0; padding: 15px">
  <h2 class="ui header">Please fill the form, allow us to generate personalised study plan for you</h2>
  <%= form_with(url: '/system/students/request_advice/form_submit', html: { class: "ui form" }) do |form| %>
    <br>
    <div class="three wide field">
      <label>Are you new student?</label>
      <%= form.select :new_or_continue, ['No','Yes'] %>
    </div>

    <br>
    <div class="actions">
      <%= form.submit "Next", class: "ui primary button"%>
    </div>
  <% end %>
</div>

app/views/students/continue_student.html.erb
<%= semantic_flash %>

<div class="six ui buttons">
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Dashboard
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/enrolments' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Enrolments
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>
  <button class="ui animated blue disabled button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/request_advice' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Request Advice
      </div>
      <div class="hidden content">
        <i class="users icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/advice_history' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Advice History
      </div>
      <div class="hidden content">
        <i class="clipboard list icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui vertical animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/help' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Help
      </div>
      <div class="hidden content">
        <i class="question circle icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated fade red button" tabindex="0" style="padding: 0">
    <%= link_to '/system/logout' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Logout
      </div>
      <div class="hidden content">
        <i class="sign-out icon"></i>
      </div>
    <% end %>
  </button>

</div>
<br/><br/><br/>

<div style="background-color: #DCE9F0; padding: 15px">
  <h2 class="ui header">Please fill the form, allow us to generate personalised study plan for you</h2>
  <%= form_with(url: '/system/students/request_advice/result', html: { class: "ui form" }) do |form| %>
    <br>
    <div class="three wide field">
      <label>Which year of your degree you want advice for?</label>
      <%= form.select :year, ['1','2','3','4'] %>
    </div>

    <div class="three wide field">
      <label>Which teaching period do you want advice for?</label>
      <%= form.select :teaching_period, ['Semester 1','Semester 2','Summer School','Winter School'] %>
    </div>

    <br>
    <div class="actions">
      <%= form.submit "Submit", class: "ui primary button"%>
    </div>

  <% end %>
</div>

app/views/students/dashboard.html.erb
<%= semantic_flash %>

<div class="six ui buttons">
  <button class="ui animated blue disabled button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Dashboard
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/enrolments' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Enrolments
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/request_advice' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Request Advice
      </div>
      <div class="hidden content">
        <i class="users icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/advice_history' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Advice History
      </div>
      <div class="hidden content">
        <i class="clipboard list icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui vertical animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/help' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Help
      </div>
      <div class="hidden content">
        <i class="question circle icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated fade red button" tabindex="0" style="padding: 0">
    <%= link_to '/system/logout' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Logout
      </div>
      <div class="hidden content">
        <i class="sign-out icon"></i>
      </div>
    <% end %>
  </button>

</div>
<br/><br/><br/>

<div style="background-color: #DCE9F0; padding: 15px">

  <h2 class="ui header">Student Profile</h2>
  <br>

  <table class="ui definition selectable table">
    <colgroup>
      <col span="1" style="width: 30%;">
      <col span="1" style="width: 70%;">
    </colgroup>

    <tbody>
    <tr>
      <td>Student ID: </td>
      <td><%= current_user.account %></td>
    </tr>
    <tr>
      <td>Name: </td>
      <td><%= current_user.name %></td>
    </tr>
    <tr>
      <td>Residency: </td>
      <td><%= current_user.residency %></td>
    </tr>
    <tr>
      <td>Qualification: </td>
      <td><%= current_user.qualification %></td>
    </tr>
    <tr>
      <td>Program: </td>
      <td><%= current_user.program %></td>
    </tr>
    <tr>
      <td>Plan: </td>
      <td><%= current_user.plan %></td>
    </tr>
    <tr>
      <td>Year: </td>
      <td><%= current_user.year %></td>
    </tr>
    <tr>
      <td>Expected completion: </td>
      <td><%= current_user.expected_completion %></td>
    </tr>

    <%unless current_user.english_exam.nil? %>
    <tr>
      <td>English Exam </td>
      <td><%= current_user.english_exam %></td>
    </tr>
    <tr>
      <td>English Score: </td>
      <td><%= current_user.english_score %></td>
    </tr>
    <% end %>

    </tbody></table>

  <%= button_to "Edit Completion Year", system_students_edit_path, :method => "get" %>

</div>
<br>

app/views/students/edit.html.erb
<%= semantic_flash %>

<div class="five ui buttons">
  <button class="ui animated blue disabled button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Dashboard
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/request_advice' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Request Advice
      </div>
      <div class="hidden content">
        <i class="users icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/advice_history' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Advice History
      </div>
      <div class="hidden content">
        <i class="clipboard list icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui vertical animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/help' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Help
      </div>
      <div class="hidden content">
        <i class="question circle icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated fade red button" tabindex="0" style="padding: 0">
    <%= link_to '/system/logout' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Logout
      </div>
      <div class="hidden content">
        <i class="sign-out icon"></i>
      </div>
    <% end %>
  </button>

</div>
<br/><br/><br/>

<div style="background-color: #DCE9F0; padding: 15px">
  <h1 class="ui center aligned header">Enter your new expected completion, in the format "2021 Semester 1"</h1>
  <%= form_with model: @student, url: system_students_update_path, method: :patch, local: true, scope: @student do |f| %>
    <div>
    <%= f.label :expected_completion %>
    <%= f.text_field :expected_completion %>
    </div>
    <div>
    <%= f.submit "Confirm Change" %>
    </div>
    <% end %>

</div>

app/views/students/enrolments.html.erb
<%= semantic_flash %>

<div class="six ui buttons">
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Dashboard
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue disabled button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/enrolments' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Enrolments
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/request_advice' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Request Advice
      </div>
      <div class="hidden content">
        <i class="users icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/advice_history' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Advice History
      </div>
      <div class="hidden content">
        <i class="clipboard list icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui vertical animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/help' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Help
      </div>
      <div class="hidden content">
        <i class="question circle icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated fade red button" tabindex="0" style="padding: 0">
    <%= link_to '/system/logout' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Logout
      </div>
      <div class="hidden content">
        <i class="sign-out icon"></i>
      </div>
    <% end %>
  </button>

</div>
<br/><br/><br/>
<div style="background-color: #DCE9F0; padding: 15px">

  <h2 class="ui header">My enrolments</h2>
  <br>
  <table class="ui table">
    <thead>
    <tr>
      <th>Course name</th>
      <th>Term</th>
      <th>Marks</th>
    </tr>
    </thead>
    <tbody>
    <% @enrolments.each do |enrolment| %>
      <tr>
        <% @courses.each do |course| %>
          <% if enrolment.course_ID == course.course_ID %>
            <td><%= course.subject_area %> <%= course.catalogue %> <%= course.name %></td>
          <%end%>
        <%end%>
        <% if enrolment.term%100== 10%>
          <td>Semester 1</td>
        <%elsif enrolment.term%100== 20%>
          <td>Semester 2</td>
        <%elsif enrolment.term%100== 5%>
          <td>Summer School</td>
        <%elsif enrolment.term%100== 15%>
          <td>Winter School</td>
        <%end%>
        <td><%= enrolment.marks %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/students/help.html.erb
<%= semantic_flash %>

<div class="six ui buttons">
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Dashboard
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/enrolments' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Enrolments
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/request_advice' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Request Advice
      </div>
      <div class="hidden content">
        <i class="users icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/advice_history' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Advice History
      </div>
      <div class="hidden content">
        <i class="clipboard list icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui vertical animated blue disabled button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/help' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Help
      </div>
      <div class="hidden content">
        <i class="question circle icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated fade red button" tabindex="0" style="padding: 0">
    <%= link_to '/system/logout' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Logout
      </div>
      <div class="hidden content">
        <i class="sign-out icon"></i>
      </div>
    <% end %>
  </button>

</div>
<br/><br/><br/>

<div style="background-color: #DCE9F0; padding: 15px">
  <h1 class="ui center aligned header">Helpful information</h1>
  <div class="ui big animated very relaxed list">
    <a class="item" href="https://www.adelaide.edu.au/"><i class="home icon"></i> University of Adelaide official website</a>
    <a class="item" href="https://www.adelaide.edu.au/degree-finder"><i class="search icon"></i>Degree finder</a>
    <a class="item" href="https://ecms.adelaide.edu.au/study-with-us/student-support/study-plans"><i class="file alternate outline
      icon"></i>Study plans</a>
  </div>
</div>

app/views/students/history.html.erb
<%= semantic_flash %>

<div class="six ui buttons">
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Dashboard
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/enrolments' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Enrolments
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/request_advice' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Request Advice
      </div>
      <div class="hidden content">
        <i class="users icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated blue disabled button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/advice_history' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Advice History
      </div>
      <div class="hidden content">
        <i class="clipboard list icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui vertical animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/help' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Help
      </div>
      <div class="hidden content">
        <i class="question circle icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated fade red button" tabindex="0" style="padding: 0">
    <%= link_to '/system/logout' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Logout
      </div>
      <div class="hidden content">
        <i class="sign-out icon"></i>
      </div>
    <% end %>
  </button>

</div>
<br/><br/><br/>

<div style="background-color: #DCE9F0; padding: 15px">
  <table class="ui fixed table">
    <thead>
    <tr>
      <th>Advice ID</th>
      <th>Date</th>
      <th>Term</th>
      <th>Detail</th>
    </tr>
    </thead>

    <% @advices.each do |advice| %>
      <tr>
        <td><%= advice.advice_ID %></td>
        <td><%= advice.date %></td>
        <td>Year <%= advice.degree_year %>, <%= advice.teaching_period %></td>
        <td>
          <%= form_with(url: '/system/students/show') do |form| %>
            <div style="display:none"><%= form.text_field :advice_id, value: advice.advice_ID, :readonly => true%></div>
            <button class="ui animated blue button" tabindex="0" style="padding: 0">
              <div class="actions">
                <div class="visible content" style="margin: 0; padding: 10px">
                  View details
                </div>
                <div class="hidden content">
                  <i class="file alternate outline icon"></i>
                </div>
              </div>
            </button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/students/new_student.html.erb
<%= semantic_flash %>

<div class="six ui buttons">
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Dashboard
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>
  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/enrolments' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Enrolments
      </div>
      <div class="hidden content">
        <i class="clipboard outline icon"></i>
      </div>
    <% end %>
  </button>
  <button class="ui animated blue disabled button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/request_advice' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Request Advice
      </div>
      <div class="hidden content">
        <i class="users icon"></i>
      </div>
    <% end %>
  </button>



  <button class="ui animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/advice_history' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Advice History
      </div>
      <div class="hidden content">
        <i class="clipboard list icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui vertical animated blue button" tabindex="0" style="padding: 0">
    <%= link_to '/system/students/help' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Help
      </div>
      <div class="hidden content">
        <i class="question circle icon"></i>
      </div>
    <% end %>
  </button>

  <button class="ui animated fade red button" tabindex="0" style="padding: 0">
    <%= link_to '/system/logout' do %>
      <div class="visible content" style="margin: 0; padding: 10px">
        Logout
      </div>
      <div class="hidden content">
        <i class="sign-out icon"></i>
      </div>
    <% end %>
  </button>

</div>
<br/><br/><br/>

<div style="background-color: #DCE9F0; padding: 15px">
  <h2 class="ui header">Please fill the form, allow us to generate personalised study plan for you</h2>
  <%= form_with(url: '/system/students/request_advice/result', html: { class: "ui form" }) do |form| %>
    <br>

    <div class="three wide field">
      <label>Have you read the study plan?</label>
      <%= form.select :study_plan, ['No','Yes'] %>
    </div>


    <div class="four wide field">
      <label>Choose you favorite subject area:</label>
      <%= form.select :subject_area, ['COMP SCI','ENG','ENTREP','ECIC','MATH','MED','CON','BUS','ARTS','LAW','ECO','DENT','ARCH','WY'] %>
    </div>


    <br>
    <div class="actions">
      <%= form.submit "Submit", class: "ui primary button"%>
    </div>
  <% end %>
</div>